### ISSUE TITLE
Add simple methods to clean OSM outputs

### ISSUE THREAD

**Issue by chahank** [osm-flex/osm-flex#15]
Many OSM queries will result in data that needs further curation, such as removing very small regions or remove duplicates. We could include these methods in this module. Only the very simple procedures could be added, and leave the more complex post-processing such as joining/simplifying road or rail networks to the already existing packages.

Example:

```
def _find_duplicates(overlap_gdf):
    indices_dupl = np.unique([index_right for index_right, index_left in zip(overlap_gdf.index_right, overlap_gdf.index_left)
                    if index_right != index_left])
    indices_dupl = indices_dupl[:int(len(indices_dupl/2))] # only first half of duplicates should be removed!
    return indices_dupl

def _remove_duplicates(orig_gdf, indices_dupl):
    indices_keep = list(set(orig_gdf.index).difference(set(indices_dupl)))
    return orig_gdf.loc[indices_keep]

def find_remove_duplicates(orig_gdf):
    if 'index' in orig_gdf.columns:
        orig_gdf = orig_gdf.drop('index', axis=1)
    overlap_gdf = orig_gdf.sjoin(orig_gdf)
    if 'index_left' not in overlap_gdf.columns:
        overlap_gdf = overlap_gdf.reset_index()
        overlap_gdf = overlap_gdf.rename({'index':'index_left'}, axis=1)  
    indices_dupl = _find_duplicates(overlap_gdf)
    return _remove_duplicates(orig_gdf, indices_dupl)   
```

**Comment by chahank** [comment]
Should I make a proposal for some of these methods?

**Comment by Evelyn-M** [comment]
here’s the corresponding example on how to use it:
```
gdf2clean = gdf2clean.reset_index(drop=True)
gdf2clean['geometry'] = gdf2clean.geometry.buffer(0.001) # ca. 100m buffer in epsg4326; decrease if you think that's too much
gdf2clean = find_remove_duplicates(gdf2clean)
gdf2clean['geometry'] = gdf2clean.geometry.centroid
```

**Comment by chahank** [comment]
A first method has been added in PR #24 . These types of methods are now part of the module `simplify` .

**Comment by chahank** [comment]
For the method `simplify.remove_small_polygons` it would be nice to have the option of a metres=True kwarg (similar to the CLIMADA interpolation functions), where min_area can hence be specified in m2, irrespective of the original projection of the gdf. Requires a check & potential re-projection of the gdf under the hood.

**Comment by Evelyn-M** [comment]
Simple "cleaning methods" were added in pull request #24 . Will close this for now, but additions are of course always welcome.
