### ISSUE TITLE
query building does not allow for extracting everything

### ISSUE THREAD

**Issue by ElcoK** [osm-flex/osm-flex#20]
The current version of the query_builder function does not allow for extracting, for example, all buildings at once. It always requires to specify which tags you would like to extract. This is problematic if you do not know yet which attributes are used within a specific area.

Original query_building function:

```
def query_b(geo_type, key_col, **val_constraint):
    """
    Builds an SQL query from the values passed to the function.
    
    Arguments:
            geo_type : Type of geometry (osm layer) to search for.
            key_col : A list of keys/columns that should be selected from the layer.
            val_constraint : A dictionary of constraints for the values. e.g. WHERE 'value'>20 or 'value'='constraint'
    Returns:
        string: A SQL query string.
    """
    query = "SELECT osm_id"
    
    for column in key_col:
        query += ", " + column

    query += " FROM " + geo_type + " WHERE "

    if val_constraint:
        constraint_clauses = []
        for key, values in val_constraint.items():
            for value in values:
                constraint_clauses.append(f"{key} {value}")
        query += " AND ".join(constraint_clauses) + " AND "
        
    query += f"{key_col[0]} IS NOT NULL"
    return query
```

osm-flex query builder:

```
def _query_builder( geo_type, constraint_dict):
    """
    This function builds an SQL query from the values passed to the extract()
    function.
    Parameters
    ---------
    geo_type : str
        Type of geometry to extract. One of [points, lines, multipolygons]
    constraint_dict :  dict
    Returns
    -------
    query : str
        an SQL query string.
    """
    # columns which to report in output
    query =  "SELECT osm_id"
    for key in constraint_dict['osm_keys']:
        query+= ","+ key
    # filter condition(s)
    query+= " FROM " + geo_type + " WHERE " + constraint_dict['osm_query']

    return query
```

**Comment by chahank** [comment]
I am not sure to understand the query you would like to do. Could you please give an example?

**Comment by ElcoK** [comment]
the original query_builder function allows for extracting all objects that have some tag (through the 'IS NOT NULL' option). In our new query_builder function, we have removed the option to extract everything that has some tag for a specific attribute. We always need to define the tags we want to extract. But this is not always desired. For example, you sometimes just want to extract all the buildings within a specific area, without knowing exactly how everything is tagged.

**Comment by ElcoK** [comment]
For example,

this was always my function to extract all buildings:

```
def buildings(osm_path):
    """
    Function to extract building polygons from OpenStreetMap    

    Arguments:
        *osm_path* : file path to the .osm.pbf file of the region 
        for which we want to do the analysis.        
    Returns:
        *GeoDataFrame* : a geopandas GeoDataFrame with all unique building polygons.    
    """
    return retrieve(osm_path, 'multipolygons',['building','amenity'])
```

This would not contain a constraint_dict, because we just want all buildings. Now this will raise an error because a specific constraint_dict is missing.

**Comment by chahank** [comment]
I see... but what is the query `query_b(geo_type, key_col, **val_constraint)` that this would result in?

**Comment by ElcoK** [comment]
`query_b('multipolygons',['building','amenity'])`. The `val_constraint` is considered to be a kwarg.
