### ISSUE TITLE
WindowsPath not recognized

### ISSUE THREAD

**Issue by jensdebruijn** [osm-flex/osm-flex#9]
Doesn't recognize path on Windows, suggested fix: 
`if isinstance(shape, (pathlib.PosixPath, pathlib.WindowsPath, str)):
`
https://github.com/ElcoK/osm-flex/blob/f60df93e8bb1d46d743825443458ababda048475/src/osm_flex/clip.py#L165

**Comment by peanutfun** [comment]
A better fix is to replace all instances of `pathlib.PosixPath` with `pathlib.Path`. According to [the docs](https://docs.python.org/3/library/pathlib.html#pathlib.Path), this should support both types of paths:

> [pathlib.Path] represents concrete paths of the system’s path flavour (instantiating it creates either a [PosixPath](https://docs.python.org/3/library/pathlib.html#pathlib.PosixPath) or a [WindowsPath](https://docs.python.org/3/library/pathlib.html#pathlib.WindowsPath)):

**Comment by Evelyn-M** [comment]
This should be fixed now through commit [c390a70](https://github.com/osm-flex/osm-flex/pull/13/commits/c390a70d4a730cd12a4a16d5d7f1d2a6910ac66a)

**Comment by Evelyn-M** [comment]
> This should be fixed now through commit [c390a70](https://github.com/osm-flex/osm-flex/pull/13/commits/c390a70d4a730cd12a4a16d5d7f1d2a6910ac66a)
